### ISSUE TITLE
PostMarshmallow.java line 37 Crash

### ISSUE THREAD

**Issue by ytheekshana** [nisrulz/lantern#8]
I get a crash on Android 9 and 7

> Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=6937, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.ytheekshana.deviceinfo/com.nabinbhandari.android.permissions.PermissionsActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)

> Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at github.nisrulz.lantern.PostMarshmallow.<init>(PostMarshmallow.java:37)
       at github.nisrulz.lantern.Lantern.initTorch(Lantern.java:129)
       at com.ytheekshana.deviceinfo.FlashlightTestActivity$1.onGranted(FlashlightTestActivity.java:83)
       at com.nabinbhandari.android.permissions.PermissionsActivity.grant(PermissionsActivity.java:228)
       at com.nabinbhandari.android.permissions.PermissionsActivity.onRequestPermissionsResult(PermissionsActivity.java:122)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7114)
       at android.app.Activity.dispatchActivityResult(Activity.java:6966)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4086)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4133)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by nisrulz** [comment]
Looks like the camera is not available.
https://github.com/nisrulz/lantern/blob/master/lantern/src/main/java/github/nisrulz/lantern/PostMarshmallow.java#L37

` cameraId = cameraManager.getCameraIdList()[0];`

i.e when trying to get the camera id at 0th position from the list of camera ids, you get ArrayIndexOutOfBounds because there are no camera listed for the device.

Can you provide more info about the device specifications? Does the device have a camera?

But I agree this case should be handled and so this is a bug.

**Comment by ytheekshana** [comment]
Here are the devices.
![1](https://user-images.githubusercontent.com/24976965/57197023-f1d04a00-6f7f-11e9-89fe-88ea19d948b1.jpg)
![2](https://user-images.githubusercontent.com/24976965/57197024-f1d04a00-6f7f-11e9-8ac8-bc0a4b800953.jpg)
![3](https://user-images.githubusercontent.com/24976965/57197025-f268e080-6f7f-11e9-8ded-ff5cca1230c2.jpg)
![4](https://user-images.githubusercontent.com/24976965/57197026-f268e080-6f7f-11e9-9e8a-2e488c585358.jpg)
![5](https://user-images.githubusercontent.com/24976965/57197027-f268e080-6f7f-11e9-8c9e-d846b1559440.jpg)
![6](https://user-images.githubusercontent.com/24976965/57197028-f3017700-6f7f-11e9-8575-f0eceaed8487.jpg)
![7](https://user-images.githubusercontent.com/24976965/57197029-f3017700-6f7f-11e9-8938-3fa7022dc369.jpg)
![8](https://user-images.githubusercontent.com/24976965/57197030-f39a0d80-6f7f-11e9-92b9-28340c6ce73b.jpg)
![9](https://user-images.githubusercontent.com/24976965/57197031-f39a0d80-6f7f-11e9-8507-81624a8d5e5e.jpg)

**Comment by nisrulz** [comment]
@ytheekshana do you have any of these devices available to you? Can you test the `develop` branch?

**Comment by ytheekshana** [comment]
> 
> 
> @ytheekshana do you have any of these devices available to you? Can you test the `develop` branch?

I don't have any of these devices.

**Comment by nisrulz** [comment]
Ok, `develop` branch is mostly unstable, so I can't issue a release with that anyways. But I can cherry-pick the small fixes for this and the other issue #9 as part of a minor patch release. 

Works?

**Comment by ytheekshana** [comment]
> 
> 
> Ok, `develop` branch is mostly unstable, so I can't issue a release with that anyways. But I can cherry-pick the small fixes for this and the other issue #9 as part of a minor patch release.
> 
> Works?

OK

**Comment by ytheekshana** [comment]
When will be the minor patch available to us. ?

**Comment by ytheekshana** [comment]
> 
> 
> Ok, `develop` branch is mostly unstable, so I can't issue a release with that anyways. But I can cherry-pick the small fixes for this and the other issue #9 as part of a minor patch release.
> 
> Works?

Is the patch ready?

**Comment by ytheekshana** [comment]
?

**Comment by WrobelKrakow** [comment]
I forked this project and merged fixes:
https://github.com/WrobelKrakow/lantern

**Comment by nisrulz** [comment]
Hi @ytheekshana 

I am really occupied at work and a lot of other things at the moment. So I am unable to make a release. 

@WrobelKrakow although your Jitpack release is in good faith, understand that the only reason the release was not made with fixes from `develop` is because the code is not stable and it crashes. I had to sit down and fix it, add another commit and then make the release. 

So TL;DR: I think to make the release via Jitpack is not going to help. Instead, if you really want to help then do submit PR to the main project with fixes to the crashing code. Making a release at most takes 5 minutes for me.

**Comment by ytheekshana** [comment]
![image](https://user-images.githubusercontent.com/24976965/60770031-4022d600-a0f4-11e9-9404-169fe0f1db30.png)
